{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}-msp
  labels:
    orgName: {{ $org.Name }}
    peerName: {{ $peer }}
data:
  config.yaml: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/config.yaml" $org.Domain $peer $org.Domain ) | b64enc }}
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/signcerts/%s.%s-cert.pem" $org.Domain $peer $org.Domain $peer $org.Domain ) | b64enc }}
  cacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/cacerts/ca.%s-cert.pem" $org.Domain $peer $org.Domain $org.Domain ) | b64enc }}
  tlscacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/tlscacerts/tlsca.%s-cert.pem" $org.Domain $peer $org.Domain $org.Domain ) | b64enc }}
  admincert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/admincerts/Admin@%s-cert.pem" $org.Domain $peer $org.Domain $org.Domain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/msp/keystore/*" $org.Domain $peer $org.Domain ) }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
  {{- end }}
---
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}
